### ISSUE TITLE
Password Failed Error

### ISSUE THREAD

**Issue by jerkjerk21** [stephanlensky/hyacinth#76]
Hello, I can't seem to figure this out properly. I have gotten a new error. You can see this below.

```dockerfile
 sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"
service-1  |
service-1  | (Background on this error at: https://sqlalche.me/e/20/e3q8)
service-1  | error: Recipe `run` failed on line 37 with exit code 1
```

**Comment by stephanlensky** [comment]
Hi, it looks again like this is an issue related to an improperly configured environment.

Please read over the getting started page carefully and ensure you've followed all of the steps: https://slensky.com/hyacinth/getting-started/

After that, feel free to let me know if you still have any questions, thanks.

**Comment by stephanlensky** [comment]
If you added the Postgres user/password environment variables after starting the database container, you may need to delete the database volume and restart the container.

To do this, run
```
docker-compose down -v
```

and then try starting the service again as normal.

**Be aware, if you have any existing data stored in Hyacinth, this will delete it.**

**Comment by jerkjerk21** [comment]
> Note that if you accidentally added the Postgres user/password environment variables _after_ starting the bot, you may need to delete the database volume and restart the container.
> 
> To do this, run
> 
> ```
> docker-compose down -v
> ```
> 
> and then try starting the bot again as normal.
> 
> **Be aware, this will delete any saved searches and filters.** (though if you are just running the bot for the first time, you shouldn't have any)

Hello, I have restarted the whole thing but I continue to get the same error:

```dockerfile
File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/aiohttp/connector.py", line 776, in __init__
service-1  |     super().__init__(
service-1  | error: Recipe `run` failed on line 37 with exit code 1
```

**Comment by stephanlensky** [comment]
That doesn't look like the same error - can you paste the full log?

**Comment by jerkjerk21** [comment]
> That doesn't look like the same error - can you paste the full log?

```dockerfile
Attaching to service-1
service-1  | 2024-02-26 00:04:17 [9] [INFO] hyacinth.discord.discord_bot Initializing bot...
service-1  | 2024-02-26 00:04:17 [9] [INFO] hyacinth.util.geo Loading geospatial datasets...
service-1  | 2024-02-26 00:04:24 [9] [INFO] hyacinth.util.geo Creating indexes...
service-1  | 2024-02-26 00:04:25 [9] [INFO] hyacinth.util.geo Done!
service-1  | Traceback (most recent call last):
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 803, in static_login
service-1  |     data = await self.request(Route('GET', '/users/@me'))
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 745, in request  
service-1  |     raise HTTPException(response, data)
service-1  | discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized
service-1  |
service-1  | The above exception was the direct cause of the following exception:
service-1  |
service-1  | Traceback (most recent call last):
service-1  |   File "<string>", line 1, in <module>
service-1  |   File "/app/hyacinth/_entry.py", line 9, in run_discord_bot
service-1  |     asyncio.run(discord_bot.start())
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
service-1  |     return runner.run(main)
service-1  |            ^^^^^^^^^^^^^^^^
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
service-1  |     return self._loop.run_until_complete(task)
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
service-1  |     return future.result()
service-1  |            ^^^^^^^^^^^^^^^
service-1  |   File "/app/hyacinth/discord/discord_bot.py", line 253, in start
service-1  |     await client.start(settings.discord_token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 777, in start  
service-1  |     await self.login(token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 612, in login  
service-1  |     data = await self.http.static_login(token)
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 807, in static_login
service-1  |     raise LoginFailure('Improper token has been passed.') from exc
service-1  | discord.errors.LoginFailure: Improper token has been passed.
service-1  | Unclosed connector
service-1  | connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f2ed087c6b0>, 9279.351616271)]']
service-1  | connector: <aiohttp.connector.TCPConnector object at 0x7f2ecbfaa1b0>
service-1  | source_traceback: Object created at (most recent call last):
service-1  |   File "<string>", line 1, in <module>
service-1  |   File "/app/hyacinth/_entry.py", line 9, in run_discord_bot
service-1  |     asyncio.run(discord_bot.start())
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
service-1  |     return runner.run(main)
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
service-1  |     return self._loop.run_until_complete(task)
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
service-1  |     self.run_forever()
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
service-1  |     self._run_once()
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1985, in _run_once
service-1  |     handle._run()
service-1  |   File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
service-1  |     self._context.run(self._callback, *self._args)
service-1  |   File "/app/hyacinth/discord/discord_bot.py", line 253, in start
service-1  |     await client.start(settings.discord_token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 777, in start  
service-1  |     await self.login(token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 612, in login  
service-1  |     data = await self.http.static_login(token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 789, in static_login
service-1  |     self.connector = aiohttp.TCPConnector(limit=0, family=socket.AF_INET)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/aiohttp/connector.py", line 776, in __init__
service-1  |     super().__init__(
service-1  | error: Recipe `run` failed on line 37 with exit code 1
service-1 exited with code 1
PS C:\Users\faith\OneDrive\Desktop\Hyacinth\hyacinth> docker-compose up service
[+] Running 3/0
 ✔ Container hyacinth-browserless-1  Running                                                                                                           0.0s 
 ✔ Container hyacinth-db-1           Running                                                                                                           0.0s 
 ✔ Container hyacinth-service-1      Created                                                                                                           0.0s 
Attaching to service-1
service-1  | 2024-02-26 00:08:04 [9] [INFO] hyacinth.discord.discord_bot Initializing bot...
service-1  | 2024-02-26 00:08:04 [9] [INFO] hyacinth.util.geo Loading geospatial datasets...
service-1  | 2024-02-26 00:08:11 [9] [INFO] hyacinth.util.geo Creating indexes...
service-1  | 2024-02-26 00:08:12 [9] [INFO] hyacinth.util.geo Done!
service-1  | Traceback (most recent call last):
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 803, in static_login
service-1  |     data = await self.request(Route('GET', '/users/@me'))
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 745, in request  
service-1  |     raise HTTPException(response, data)
service-1  | discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized
service-1  |
service-1  | The above exception was the direct cause of the following exception:
service-1  |
service-1  | Traceback (most recent call last):
service-1  |   File "<string>", line 1, in <module>
service-1  |   File "/app/hyacinth/_entry.py", line 9, in run_discord_bot
service-1  |     asyncio.run(discord_bot.start())
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
service-1  |     return runner.run(main)
service-1  |            ^^^^^^^^^^^^^^^^
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
service-1  |     return self._loop.run_until_complete(task)
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
service-1  |     return future.result()
service-1  |            ^^^^^^^^^^^^^^^
service-1  |   File "/app/hyacinth/discord/discord_bot.py", line 253, in start
service-1  |     await client.start(settings.discord_token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 777, in start  
service-1  |     await self.login(token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 612, in login  
service-1  |     data = await self.http.static_login(token)
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 807, in static_login
service-1  |     raise LoginFailure('Improper token has been passed.') from exc
service-1  | discord.errors.LoginFailure: Improper token has been passed.
service-1  | Unclosed connector
service-1  | connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f11a92d10d0>, 9505.967533902)]']
service-1  | connector: <aiohttp.connector.TCPConnector object at 0x7f11afe2e150>
service-1  | source_traceback: Object created at (most recent call last):
service-1  |   File "<string>", line 1, in <module>
service-1  |   File "/app/hyacinth/_entry.py", line 9, in run_discord_bot
service-1  |     asyncio.run(discord_bot.start())
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
service-1  |     return runner.run(main)
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
service-1  |     return self._loop.run_until_complete(task)
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
service-1  |     self.run_forever()
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
service-1  |     self._run_once()
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1985, in _run_once
service-1  |     handle._run()
service-1  |   File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
service-1  |     self._context.run(self._callback, *self._args)
service-1  |   File "/app/hyacinth/discord/discord_bot.py", line 253, in start
service-1  |     await client.start(settings.discord_token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 777, in start  
service-1  |     await self.login(token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 612, in login  
service-1  |     data = await self.http.static_login(token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 789, in static_login
service-1  |     self.connector = aiohttp.TCPConnector(limit=0, family=socket.AF_INET)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/aiohttp/connector.py", line 776, in __init__
service-1  |     super().__init__(
service-1  | error: Recipe `run` failed on line 37 with exit code 1
```

**Comment by jerkjerk21** [comment]
> That doesn't look like the same error - can you paste the full log?

```dockerfile
Attaching to service-1
service-1  | 2024-02-26 00:08:04 [9] [INFO] hyacinth.discord.discord_bot Initializing bot...
service-1  | 2024-02-26 00:08:04 [9] [INFO] hyacinth.util.geo Loading geospatial datasets...
service-1  | 2024-02-26 00:08:11 [9] [INFO] hyacinth.util.geo Creating indexes...
service-1  | 2024-02-26 00:08:12 [9] [INFO] hyacinth.util.geo Done!
service-1  | Traceback (most recent call last):
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 803, in static_login
service-1  |     data = await self.request(Route('GET', '/users/@me'))
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 745, in request  
service-1  |     raise HTTPException(response, data)
service-1  | discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized
service-1  |
service-1  | The above exception was the direct cause of the following exception:
service-1  |
service-1  | Traceback (most recent call last):
service-1  |   File "<string>", line 1, in <module>
service-1  |   File "/app/hyacinth/_entry.py", line 9, in run_discord_bot
service-1  |     asyncio.run(discord_bot.start())
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
service-1  |     return runner.run(main)
service-1  |            ^^^^^^^^^^^^^^^^
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
service-1  |     return self._loop.run_until_complete(task)
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
service-1  |     return future.result()
service-1  |            ^^^^^^^^^^^^^^^
service-1  |   File "/app/hyacinth/discord/discord_bot.py", line 253, in start
service-1  |     await client.start(settings.discord_token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 777, in start  
service-1  |     await self.login(token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 612, in login  
service-1  |     data = await self.http.static_login(token)
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 807, in static_login
service-1  |     raise LoginFailure('Improper token has been passed.') from exc
service-1  | discord.errors.LoginFailure: Improper token has been passed.
service-1  | Unclosed connector
service-1  | connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f11a92d10d0>, 9505.967533902)]']
service-1  | connector: <aiohttp.connector.TCPConnector object at 0x7f11afe2e150>
service-1  | source_traceback: Object created at (most recent call last):
service-1  |   File "<string>", line 1, in <module>
service-1  |   File "/app/hyacinth/_entry.py", line 9, in run_discord_bot
service-1  |     asyncio.run(discord_bot.start())
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
service-1  |     return runner.run(main)
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
service-1  |     return self._loop.run_until_complete(task)
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
service-1  |     self.run_forever()
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
service-1  |     self._run_once()
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1985, in _run_once
service-1  |     handle._run()
service-1  |   File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
service-1  |     self._context.run(self._callback, *self._args)
service-1  |   File "/app/hyacinth/discord/discord_bot.py", line 253, in start
service-1  |     await client.start(settings.discord_token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 777, in start  
service-1  |     await self.login(token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 612, in login  
service-1  |     data = await self.http.static_login(token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 789, in static_login
service-1  |     self.connector = aiohttp.TCPConnector(limit=0, family=socket.AF_INET)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/aiohttp/connector.py", line 776, in __init__
service-1  |     super().__init__(
service-1  | error: Recipe `run` failed on line 37 with exit code 1
service-1 exited with code 1
```

**Comment by stephanlensky** [comment]
Yeah, I don't see anything about the postgres password authentication failure anymore. This is the new error:

```
discord.errors.LoginFailure: Improper token has been passed.
```

It looks like there is something wrong with how you are setting your Discord bot token. Either you didn't provide one, or the token you provided is invalid.

**Comment by jerkjerk21** [comment]
> Yeah, I don't see anything about the postgres password authentication failure anymore. This is the new error:
> 
> ```
> discord.errors.LoginFailure: Improper token has been passed.
> ```
> 
> It looks like there is something wrong with how you are setting your Discord bot token. Either you didn't provide one, or the token you provided is invalid.

Hello, I have fixed error but now I'm getting a new one...

```dockerfile
Attaching to service-1
service-1  | 2024-02-26 00:18:40 [8] [INFO] hyacinth.discord.discord_bot Initializing bot...
service-1  | 2024-02-26 00:18:40 [8] [INFO] hyacinth.util.geo Loading geospatial datasets...
service-1  | 2024-02-26 00:18:47 [8] [INFO] hyacinth.util.geo Creating indexes...
service-1  | 2024-02-26 00:18:49 [8] [INFO] hyacinth.util.geo Done!
service-1  | Traceback (most recent call last):
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 803, in static_login
service-1  |     data = await self.request(Route('GET', '/users/@me'))
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 745, in request  
service-1  |     raise HTTPException(response, data)
service-1  | discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized
service-1  |
service-1  | The above exception was the direct cause of the following exception:
service-1  |
service-1  | Traceback (most recent call last):
service-1  |   File "<string>", line 1, in <module>
service-1  |   File "/app/hyacinth/_entry.py", line 9, in run_discord_bot
service-1  |     asyncio.run(discord_bot.start())
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
service-1  |     return runner.run(main)
service-1  |            ^^^^^^^^^^^^^^^^
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
service-1  |     return self._loop.run_until_complete(task)
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
service-1  |     return future.result()
service-1  |            ^^^^^^^^^^^^^^^
service-1  |   File "/app/hyacinth/discord/discord_bot.py", line 253, in start
service-1  |     await client.start(settings.discord_token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 777, in start  
service-1  |     await self.login(token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 612, in login  
service-1  |     data = await self.http.static_login(token)
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 807, in static_login
service-1  |     raise LoginFailure('Improper token has been passed.') from exc
service-1  | discord.errors.LoginFailure: Improper token has been passed.
service-1  | Unclosed connector
service-1  | connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7ff4b15c2930>, 10142.78894655)]']
service-1  | connector: <aiohttp.connector.TCPConnector object at 0x7ff4b5bf0a70>
service-1  | source_traceback: Object created at (most recent call last):
service-1  |   File "<string>", line 1, in <module>
service-1  |   File "/app/hyacinth/_entry.py", line 9, in run_discord_bot
service-1  |     asyncio.run(discord_bot.start())
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
service-1  |     return runner.run(main)
service-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
service-1  |     return self._loop.run_until_complete(task)
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
service-1  |     self.run_forever()
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
service-1  |     self._run_once()
service-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1985, in _run_once
service-1  |     handle._run()
service-1  |   File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
service-1  |     self._context.run(self._callback, *self._args)
service-1  |   File "/app/hyacinth/discord/discord_bot.py", line 253, in start
service-1  |     await client.start(settings.discord_token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 777, in start  
service-1  |     await self.login(token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/client.py", line 612, in login  
service-1  |     data = await self.http.static_login(token)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/discord/http.py", line 789, in static_login
service-1  |     self.connector = aiohttp.TCPConnector(limit=0, family=socket.AF_INET)
service-1  |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/aiohttp/connector.py", line 776, in __init__
service-1  |     super().__init__(
service-1  | error: Recipe `run` failed on line 37 with exit code 1
service-1 exited with code 1
```

**Comment by stephanlensky** [comment]
Did you mean to paste something else? This looks like the same error still

**Comment by jerkjerk21** [comment]
> Did you mean to paste something else? This looks like the same error still

I reset my Discord Bot Token and pasted it into the code although it's showing the same error.

**Comment by edisonmamani176-source** [comment]
encontre una aplicacion que hace lo mismo con mas funcionalidades talvez te sirva "https://firupost.netlify.app/docs" espero te ayude
